### ISSUE TITLE
Input devices working as output ones

### ISSUE THREAD

**Issue by Genarito** [vonsim/vonsim#24]
Hi, master of the universe!

If you set up PA as input and send data to it the simulator moves the switches! There are two problems here IMHO:

1. If some PIO port is set as input should not send data to the device.
2. If some device is input only, even if the developer configures the PIO port as output, the data should be ignored by the device (in this case, the switches).

**Steps to reproduce:**

```
ORG 2000H
MOV AL, 11111111B
OUT 32H, AL

OUT 30H, AL ; This turns on all the switches

INT 0
END
```

**Comment by facundoq** [comment]
Noted, this shouldn't happen.
