### ISSUE TITLE
Interrupt routine call / flag register stacking misbehaviour

### ISSUE THREAD

**Issue by ruskofulanito** [vonsim/vonsim#25]
After interruption handling routine call, flag register is stacked with incorrect values.

Consider the following code:
```x86asm
IDTIMER EQU 10
EOI EQU 20H
IMR EQU 21H
TIMER EQU 25H
CONT EQU 10H
COMP EQU 11H

ORG 40
IP_TIMER DW SUB_TIMER

ORG 3000H
SUB_TIMER: MOV AL, 20H
OUT EOI, AL
IRET

ORG 2000H
MOV DL, 0
CLI
MOV AL, 0FDH
OUT IMR, AL
MOV AL, IDTIMER
OUT TIMER, AL
MOV AL, 3
OUT COMP, AL
MOV AL, 0
OUT CONT, AL
STI
LOOP: CMP DL, 1
JZ LOOP
INT 0
END
```
When timer interruption gets handled, `CMP DL, 1` was executed with flags=1010 (C,S) but 00000011 got pushed to the stack.
After IRET execution, IP is set to 2026H and flags register is set to incorrect value.

If you change `CMP DL, 1` to `CMP DL, 0` in which case execution is intended to continue the LOOP, stacked flags are 0100 (O) although result after comparison was 0001 (Z) and so program ends after not taking JZ LOOP as intended.

Attached image shows stack state after handling routine got called, and flags register value that were meant to be pushed (`CMP DL, 1` variant)
![Captura de pantalla 2021-10-04 a la(s) 13 46 54](https://user-images.githubusercontent.com/17864597/135892570-0594aba1-00a8-41d1-8801-9178fdea7bc6.png)

The following image shows the `CMP DL, 0` version
![Captura de pantalla 2021-10-04 a la(s) 14 03 49](https://user-images.githubusercontent.com/17864597/135893666-98935f89-49b4-41e8-b344-41fe5673eb59.png)

Russian regards

**Comment by facundoq** [comment]
Solved by pull request #27
