### ISSUE TITLE
UI Changes

### ISSUE THREAD

**Issue by facundoq** [vonsim/vonsim#30]
1- Poner config en menu colapsable, incluir opción de memoria y dispositivos, y también link a doc y github. Subir estado de ejecución a mismo nivel que el logo
2- F10 estilo de botón (interrupt en hover)
3- Poner leds en Rojo
4- CPU primero y memoria 2da
5- Hover/click de celdas de memoria más explicado: Indicar que el nro es la memoria, y poner como el vonsim todas las representaciones
6- Memoria: columnas en cebra 
7- Consola: Fondo negro, letras monospace verdes?
8- Impresora:  Efecto color papel, letra tipo máquina de escribir

**Comment by facundoq** [comment]
Barra de scroll vertical en consola e impresora.
Controles de impresora arriba y no a la izquierda de la impresora.
Linea de abajo de estado -> texto alineado a la derecha

**Comment by facundoq** [comment]
Añadir botón para reportar problemas en la configuración.

**Comment by JuanM04** [comment]
- [ ] Poner config en menu colapsable, incluir opción de memoria y dispositivos, y también link a doc y github. Subir estado de ejecución a mismo nivel que el logo
- [ ] F10 estilo de botón (interrupt en hover)
- [ ] Poner leds en Rojo
- [ ] CPU primero y memoria 2da
- [ ] Hover/click de celdas de memoria más explicado: Indicar que el nro es la memoria, y poner como el vonsim todas las representaciones
- [ ] Memoria: columnas en cebra
- [ ] Consola: Fondo negro, letras monospace verdes?
- [ ] Impresora: Efecto color papel, letra tipo máquina de escribir
- [ ] Barra de scroll vertical en consola e impresora.
- [ ] Controles de impresora arriba y no a la izquierda de la impresora.
- [ ] Linea de abajo de estado -> texto alineado a la derecha
- [ ] Añadir botón para reportar problemas en la configuración.
