### ISSUE TITLE
[bug] Unable to visualize cells near the end of the memory table at non-default zoom level

### ISSUE THREAD

**Issue by b-Tomas** [vonsim/vonsim#31]
Edit because of a couple of things I had not realized.

My default zoom level is 80%, at which the memory table stops working properly and never shows the end of the table. If you look for 3FFFh, the last column will not show up.
There is no obvious way of scrolling manually across the memory table as a workaround either.

[Screencast from 15-04-23 00:01:22.webm](https://user-images.githubusercontent.com/41840767/232230581-e76f6c18-ac88-4d4d-ad76-e3bfc7dc9e93.webm)

# Expected behaviour
Any valid value in the memory address search box should recenter the memory table so that the contents of the cell can be observed. For 3FFFh, it should show the last column (3FFAh to 3FFFh) at the right hand side of the table, but at different zoom levels it does not.

# Steps to reproduce
Try looking at the contents of 3FFFh with a zoom level different than 100% on your browser

# Platform
- Firefox 111.0.1
- Pop OS 22.04 LTS
- https://vonsim.github.io/preview/

**Comment by facundoq** [comment]
Thanks Tomás, we're working on a full redesign that solves this and other
issues, you can test it at:

 https://vonsim.github.io/preview/

**Comment by JuanM04** [comment]
Fixed in 6e870a7, thanks for the issue!
