### ISSUE TITLE
Timer deja de funcionar luego detener el programa

### ISSUE THREAD

**Issue by fabriziogirardi** [vonsim/vonsim#43]
El timer deja de funcionar al poner el modo "iniciar hasta el final". La solución que encontré cuando el error o jefe, es ejecutar una instrucción, ver que el timer se mueva, y luego de la primera instrucción usar "iniciar hasta el final" y ahí sí funciona correctamente. No encontré vínculo alguno con el contenido del código y el problema.

**Comment by JuanM04** [comment]
Buenas, muchas gracias por reportar el error!

No estaría pudiendo replicar el problema. ¿Podrías enviar un video del problema? Si usás Windows 11, viene instalado _Snipping Tool_ (o _Recortes_) que te deja grabar un video fácilmente

**Comment by fabriziogirardi** [comment]
La próxima vez que me ocurra, lo grabo. El error ocurre, hasta ahora, de manera aleatoria. Resolviendo ejercicios capaz ocurre, y me guardo el código, sigo al otro día resolviendo el ejercicio, y usando el mismo código que el día anterior había dejado de andar el timer, al otro día anda perfecto.

**Comment by fabriziogirardi** [comment]
Ahí tocando pude encontrar como reproducirlo.

- Presionar en "iniciar una instrucción".
- Presionar "Detener" para reiniciar todo a cero.
- Presionar "Iniciar hasta el final".
En este momento, el timer no corre más. La única manera de que ande es poner "Iniciar una instruccion" y luego poner "Iniciar hasta el final" sin poner "Detener" en el medio, y ahí si funciona el timer. Fijate si podés reproducirlo.

**Comment by JuanM04** [comment]
Muchas gracias! El error venia por parte de react-spring: cuando una animación está pausada y se la detiene, al empezarla de nuevo sigue pausada (súper intuitivo)

**Comment by fabriziogirardi** [comment]
Mismas condiciones, acaba de ocurrir de nuevo. Cuando se empieza a interrumpir, deja de funcionar hasta que se haga una instrucción individual.

Uploading Grabación 2023-09-12 145922.mp4…

**Comment by JuanM04** [comment]
Qué raro. En las mismas condiciones, ahora a mí me anda. Por si acaso, ¿probaste cerrando la pestaña del vonsim y volviéndola a abrir, así te sale el cartel de "actualizar"? Me suele pasar en mi laptop que la cierro, la abro y no se actualiza.

Si así persiste, pasame el código y lo pruebo.

**Comment by fabriziogirardi** [comment]
Ahí probe en firefox y me anda bien, pero en chrome me anda mal. Siendo así, me suena a que debe ser problema de la caché de chrome.
