### ISSUE TITLE
Hola quiero reportar lo que imagino es un error con impresora handshake, en los videos de la catedra se usa este metodo y se ve como el simulador es capaz de hacerlo correctamente, sin embargo en estos casos donde se produce la interrupcion pero no se le es enviado nada a DATO(40h) la impresora no vuelve a emitir interrupciones y se queda en el pool del programa principal, un saludo! 

### ISSUE THREAD

**Issue by patrici06** [vonsim/vonsim#50]
<details>
  <summary>Información extra (POR FAVOR, NO BORRAR)</summary>

  **Versión**: [3aaa556](https://github.com/vonsim/vonsim/commit/3aaa556)

  #### Programa

  ```asm
  EOi equ 20h
IMR equ 21h
Dato equ 40h
estado equ 41h
int2 equ 26h
org 40
etiqueta dw Interrupcion

org 1000h
Cadena db "WEdsdaRTAo4059"
Fin db ?
org 1500h
Boolean db 0
org 3000h
Seleccion: mov boolean,0
cmp cl,61h
jns volver
cmp cl,41h
js volver
mov boolean,1
volver: ret
Interrupcion:
mov cl,[bx]
call seleccion
cmp boolean,1
jnz no
mov al, [bx]
out Dato,al
no: inc bx
dec dl
jnz back
mov al,11111111b
out IMR,al
back: mov al, 0h; Lineas Para parchear el error
out Dato,al; Lineas Para parchear el error
mov al,20h
out EOI,al
iret
org 2000h
CLI
in al, EStado
or al,80h
out Estado,al
mov al,11111011b
out IMR,al
mov al,10
out INT2,al
mov bx,offset cadena
mov dl, offset fin- offset cadena
sti
pool:
cmp dl,0
jnz pool
int 0
end
  ```

  #### Configuración

  - **language**: es
  - **editorFontSize**: 14
  - **dataOnLoad**: randomize
  - **devices**: handshake
  - **animations**: false
  - **executionUnit**: 1.4519049980260073
  - **clockSpeed**: 1000
  - **printerSpeed**: 499.99999999999983
  - **filterBightness**: 1
  - **filterContrast**: 1
  - **filterInvert**: false
  - **filterSaturation**: 1
  
</details>

**Comment by AndoniZubimendi** [comment]
Hola, este problema esta reportado también en #51 , fijate en el comentario. 

Basicamente el tema es que la interrupción del handshake ocurre cuando la impresora pasa de estar "ocupada" a "desocupada", si vos salís de la interrupción sin imprimir ese evento no vuelve a ocurrir.

Saludos

**Comment by JuanM04** [comment]
Gracias @AndoniZubimendi! Cierro este issue, pero pueden seguir comentando
