### ISSUE TITLE
impresora no esta funcionando, a veces aparece con papel y otras veces sin papel y no imprime

### ISSUE THREAD

**Issue by paulprk** [vonsim/vonsim#51]
<details>
  <summary>Debug info (PLEASE, DO NOT DELETE)</summary>

  **Version**: [3aaa556](https://github.com/vonsim/vonsim/commit/3aaa556)

  #### Program

  ```asm
  EOI EQU 20H
IMR EQU 21H
INT2 EQU 26H
HD_DATO EQU 40H
HD_ESTADO EQU 41H

ORG 1000H
CADENA DB "123456789"
FIN DB ?

ORG 40
DW RUT_HD

ORG 4000H
SELECCIONADO:AND AL,1
JZ PAR
MOV DH,0
DEC CL
JMP FINALIZAR
PAR:MOV DH,1
FINALIZAR:RET

ORG 3000H
RUT_HD:PUSH AX
MOV AL,[BX]
INC BX
CALL SELECCIONADO
CMP DH,1
JNZ SEGUIR

MOV AL,[BX]
OUT HD_DATO,AL

DEC CL
JNZ SEGUIR

FINAL:MOV AL,0FFH
OUT IMR,AL

SEGUIR:MOV AL,EOI
OUT EOI,AL
POP AX
IRET

ORG 2000H
MOV BX,OFFSET CADENA
MOV CL,OFFSET FIN-OFFSET CADENA
CLI
MOV AL,11111011B
OUT IMR,AL
MOV AL,10
OUT INT2,AL
IN AL,HD_ESTADO
OR AL,80H
OUT HD_ESTADO,AL
STI
LOOP:CMP CL,0
JNZ LOOP
INT 0
END

  ```

  #### Settings

  - **language**: en
  - **editorFontSize**: 14
  - **dataOnLoad**: randomize
  - **devices**: handshake
  - **animations**: true
  - **executionUnit**: 3.9244012100723804
  - **clockSpeed**: 1238.9954984596784
  - **printerSpeed**: 1007.7699462974344
  - **filterBightness**: 1
  - **filterContrast**: 1
  - **filterInvert**: false
  - **filterSaturation**: 1
  
</details>

**Comment by AndoniZubimendi** [comment]
Hola, el problema que estas teniendo no esta en el simulador. Sino en como estás usando la interrupción del handshake.

Estas usando hanshake por interrupciones, eso esta bien configurado. El problema es que en el momento de recibir la interrupción, el manejador imprime o no dependiendo si cumple con la función de SELECCIONADO. Cuando el manejador de interrupción sale sin haber impreso algo, nunca más va a ser invocado, ya que la impresora esta "desocupada" y no va a volver a ocurrir el evento de desocuparse. 

En otras palabras, la interrupción del handshake ocurre cuando la impresora deja de estar ocupada y pasa a estar libre (el bit BUSY pasa de 1 a 0), eso ocurre la primera vez y si no se manda nada a imprimir, esa condición no vuelve a ocurrir, por lo tanto la interrupción no vuelve a dispararse.

Una posible solución para ese programa podría ser iterar en la cadena buscando el siguiente carácter seleccionado e imprimirlo. En caso de llegar al final de la cadena, retornar sin imprimir. Que en este último caso no se genere una próxima interrupción no es un problema para el programa. Porque una vez que termine, el programa debería finalizar.

**Comment by JuanM04** [comment]
Gracias @AndoniZubimendi! Cierro este issue, pero pueden seguir comentando
