### ISSUE TITLE
Valor de la pila al llamar a una interrupción

### ISSUE THREAD

**Issue by ruiz-jose** [vonsim/vonsim#58]
Hola, queria consultar/informar que cuando se invoca a una interrupción, por ejemplo INT 7, la dirección de la proxima instrucción y de los flags se guardan en la pila, entiendo que por compatibilidad se almacenan 2 bytes para la direccion de la proxima intrucción.
Mi consulta es la siguiente, consideremos el siguiente ejemplo:
  ```asm 
int 7 ;--> direccción 2007h
mov al, 6  ;--> direccción 2009h
 ```
Cuando se ejecuta la interrupcion **no logro encontrar en la pila el valor 2009h** que es la proxima instrucción a ejecutar despues de ejecutar la interrupción. Sin embargo una vez que termina la ejecutar la interrupción aparece en el IP el valor 2009h. 
Espero se entienda mi consulta.
Muchas gracias por todo el trabajo que llevan adelante con el VonSim, es super didactico.

<details>
  <summary>Información extra (POR FAVOR, NO BORRAR)</summary>

  **Versión**: [4977b11](https://github.com/vonsim/vonsim/commit/4977b11)

  #### Programa

  ```asm
org 1000h
msg db "Hola!"

org 2000h
mov bx, offset msg
mov al, 5
int 7
mov al, 6  --> direccción 2009h
end


  ```

  #### Configuración

  - **language**: es
  - **editorFontSize**: 14
  - **dataOnLoad**: randomize
  - **devices**: keyboard-and-screen
  - **animations**: false
  - **executionUnit**: 150
  - **clockSpeed**: 1000
  - **printerSpeed**: 5000
  - **filterBightness**: 1
  - **filterContrast**: 1
  - **filterInvert**: false
  - **filterSaturation**: 1
  
</details>

**Comment by facundoq** [comment]
Hola José! ¿Qué url estás usando?
Yo veo que en la última versión está la dirección de retorno en la pila:

![image](https://github.com/vonsim/vonsim/assets/1576711/6ac7342b-4149-4d80-8491-9ad34f36c31b)

![image](https://github.com/vonsim/vonsim/assets/1576711/a700dfed-bb25-4314-80c4-9505081ae1d2)

**Comment by ruiz-jose** [comment]
Gracias Facundo por responder!!! Me confundi, estaba acustumbrando al simulador anterior que muestra de manera hoziontal las  palabras en la pila.. en conclusión estaba mirando mal la memoria. No preste atención..Mil gracias. Un abrazo.

**Comment by facundoq** [comment]
Si, me pasa también! Lo anotamos para una versión futura, mejorar el diseño de la memoria para siga aprovechando como ahora el espacio horizontal pero que sea más intuitivo para buscar direccionjes.
